
name: 'jaffle_shop'
version: '0.1'
profile: 'my-snowflake-db'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

      #on-run-end: ["{{update_source_id()}}","{{update_batch_id()}}"]

models:
  jaffle_shop:
      materialized: table
