my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: df61283.us-central1.gcp
      user: pratuppal
      role: ACCOUNTADMIN
      password: Leap@2021
      database: LEAP_STAGING
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 1
      client_session_keep_alive: False
