version: 2

models:
  - name: dbt_table
    description: This table has basic information

    columns:
      - name: id
        description: This is a unique identifier for each row
        tests:
          - unique
          - not_null

